#=========================
# Configurações básicas
#=========================
backend = "glx";

# glx-no-stencil = true;

vsync = true;
use-damage = true;
# refresh-rate = 0;

detect-rounded-corners = true;
detect-client-opacity = true;


#=========================
# Sombras
#=========================
shadow = true;
shadow-radius = 12;
shadow-opacity = .95;
shadow-offset-x = -5;
shadow-offset-y = 0;
# shadow-exclude = []

#=========================
# Fading
#=========================
fading = true;
fade-in-step = 0.5;
fade-out-step = 0.3;
fade-delta = 10;


#=========================
# Transparência
#=========================
frame-opacity = .7;
active-opacity = 1;

inactive-opacity = .9;
inactive-opacity-override = false;

opacity-rule = [ "100:class_g = 'firefox'"];


#=========================
# Desfoque
#=========================
blur-background = true;
blur-kern = "3x3box";
blur-method = "dual_kawase";
blur-strength = 8.0;
blur-deviation = 2.0;

# blur-background-frame = true;
# blur-background-fixed = false;



#=========================
# Wintypes
#=========================
wintypes: {
  # ... outras configurações de transparência ...
  tooltip = { fade = false; };
  # Adicione a linha abaixo para a classe da Polybar
  dock = { shadow = false; };
};

