#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d          

xsetroot -cursor_name left_ptr

bspc config border_width         1
bspc config window_gap          15

bspc config automatic_scheme spiral
#bspc config initial_polarity fist_child
bspc config split_ratio          0.5

bspc config normal_border_color "#000000"
bspc config focused_border_color "#5FB4DE"
bspc config focus_follows_pointer true


#==================
# WALLPAPER
#==================
# altere o wallaper pelo bash, execute:
# feh --bg-scale /home/emmyvinte/Imagens/(SEU_WALLPAPER)
${HOME}/.fehbg


#==================
# COMPOSITOR
#==================
# use 1 compositor por vez
# picom --config $HOME/.config/picom/picom.conf --vsync --experimental-backends &
picom &


#==================
# GUI
#==================
polybar example -r
dunst &
# sxhkd running
numlockx on &
exec setxkbmap br


#==================
# APPS
#==================
flameshot &


